### ISSUE TITLE
"Axe is already running" warnings when using `it.each`

### ISSUE THREAD

**Issue by swissspidy** [NickColley/jest-axe#259] opened 2022-11-23 14:41 UTC
With jest-axe 7.0.0 I'm suddenly getting the following warning:

```
Axe is already running. Use `await axe.run()` to wait for the previous run to finish before starting a new run.
```

But only for tests using `it.each`.

All other tests are fine.

The affected test is pretty simple and just renders a React component and then calls axe, of course with `await axe.run()`

```js

import { axe } from 'jest-axe';

// ...

it.each(...)('render component', async (param) {
  const { container } = render(...) // from Testing Library
  const results = await axe(container);
  expect(results).toHaveNoViolations();
});
```

This is with using the `--runInBand` CLI option, in case that makes a difference.

**Comment by swissspidy** [comment] 2022-11-23 14:59
Yes. I noticed because Dependabot wanted to update from v6 to 7 and tests started failing.

**Comment by AlanSl** [comment] 2022-11-30 21:09
I'm seeing something similar (in both `7.0.0` and `6.0.0`) when running multiple test suites concurrently. 

Is the warning message incorrect? There doesn't seem to be any function "`axe.run`" - adding `await axe.run()` fails with:

> TypeError: _jestAxe.axe.run is not a function

**Comment by NickColley** [comment] 2022-12-02 12:38
Might be that we need to expose a way to return the promise they describe, I imagine one work around is to run tests serially (not at the same time) until this is resolved.

**Comment by NickColley** [comment] 2022-12-03 10:02
I can't reproduce this with the following, can any of you make a reproduction?

```js
const { axe } = require("jest-axe");

const failingHtmlExample = `
    <html>
    <body>
        <a href="#"></a>
    </body>
    </html>
`;

const tests = Array(100).fill([failingHtmlExample]);

describe("concurrent", () => {
  test.each(tests)("%s", async (html) => {
    const results = await axe(html);
    const violation = results.violations[0];
    expect(violation.id).toBe("link-name");
    expect(violation.description).toBe("Ensures links have discernible text");
  });
});

```

**Comment by will-stone** [comment] 2023-01-10 10:17
I've just started seeing this error on our GitLab CI, but it runs fine on local macOS. Maybe a Linux thing? 🤷‍♂️

**Comment by will-stone** [comment] 2023-01-10 10:20
Oh, and it doesn't always happen; I just re-ran the job and it passed fine 😬

**Comment by NickColley** [comment] 2023-01-10 10:23
If you can create a reproducible issue I'll look into it otherwise closing this out for now cheers Will :)

**Closed by NickColley** 2023-01-10 10:23 UTC
