### ISSUE TITLE
jest.useFakeTimers causes test timeout

### ISSUE THREAD

**Issue by dbasilio** [nickcolley/jest-axe#156] opened 2021-02-09 17:21 UTC
Here is a simple repro, the test below passes. If you uncomment the `jest.useFakeTimers()` in the `beforeEach` the test will timeout no matter what else you do.

```js
import React from 'react'
import { mount } from 'enzyme'

import { toHaveNoViolations, axe } from 'jest-axe'

expect.extend(toHaveNoViolations)

const MyComponent = () => {
    return <div></div>
}

describe('myComponent', () => {
    beforeEach(() => {
        //jest.useFakeTimers()
    })

    it('does not hit a timeout', async () => {
        const wrapper = mount(<MyComponent />)

        const result = await axe(wrapper.getDOMNode())

        expect(result).toHaveNoViolations()
    })
})
```

Version Details:
jest-axe: 4.1.0
jest: 26.6.3
axe-core: 4.1.1

**Comment by dbasilio** [comment] 2021-02-09 20:01
For those looking for a workaround to the problem:

```js
it('does not hit a timeout', (done) => {
    const wrapper = mount(<MyComponent />)

    axe(wrapper.getDOMNode()).then(axeResult => {
        expect(axeResult).toHaveNoViolations()
        done()
    })

    jest.advanceTimersByTime(1000)
})
```

The `jest.advanceTimersByTime` will log a console error if fakeTimers is not being used.

**Comment by dsamburskyi** [comment] 2021-02-10 21:06
@dbasilio I had similar issue. Simply putting `jest.useRealTimers();` in the axe test helped. 
Interestingly `afterEach(() => jest.useRealTimers());` doesn't work.

**Comment by dbasilio** [comment] 2021-02-10 22:41
@dsamburskyi If your `jest.useFakeTimers()` call appears in a `beforeAll` instead of a `beforeEach` then calling `jest.useRealTimers()` could make tests non-deterministic depending on the order run. `afterEach` runs after the test has completed, so the timeout would have already occurred.

**Comment by peterlawless** [comment] 2021-11-04 21:00
My solution is to `just.useRealTimers()` run my axe tests, then call `jest.useFakeTimers` within the same test block.  Even with `jest.useFakeTimers()` in a `beforeEach` block, I ran into issues where `jest.advanceTimersByTime()` would execute _twice_ and throw off my tests if I did not close out the axe tests with `jest.useFakeTimers()`!

**Comment by nickcolley** [comment] 2022-03-07 18:31
This seems to be an issue that is caused by timers in your own code being tested so will close this out unless you know of something we should change in this package itself :)

Thank you for posting the useful workarounds for people Googling to find, appreciated.

**Closed by nickcolley** 2022-03-07 18:31 UTC

**Comment by dbasilio** [comment] 2022-03-07 19:40
Well ideally using fake timers doesn't cause the test to time out. This is an annoying issue to run into and annoying to solve. It points to something being done with timers in this package that is causing that behaviour.

Without my solution posted above (which is a fairly un-intuitive piece of code IMO), you need to isolate a11y tests to a separate test file, or a separate describe block. Both of those are not ideal solutions. The package is `jest-axe` but if you use a fairly common jest feature _in your other tests_ this package breaks.

**Comment by merrywhether** [comment] 2022-03-17 00:07
We've added a wrapper function that makes usage seamless in our repo (we have `timers: 'modern'` in our config).

```ts
export async function axe(...args: Parameters<JestAxe>): ReturnType<JestAxe> {
  const [results] = await Promise.all([
    jestAxe(...args),
    new Promise<void>((resolve) => {
      jest.runAllTimers();
      resolve();
    }),
  ]);

  return results;
}
```

This works with both real and fake timers, but Jest warns for real timers because `runAllTimers` is a noop then. Unfortunately, Jest doesn't appear to expose a way to programmatically detect what type of timers currently are in use. This worked as a way to detect fake timers silence the error:

```
if (jest.getRealSystemTime() !== Date.now()) {
  jest.runAllTimers();
}
resolve();
```
but it's pretty brittle for a variety of reasons. Maybe just exposing a second export that covers the Fake Timers use-case would be the best path forward? I'd be happy to PR that if there's interest. The hardest part of that would be the naming (`axeFT`, `axeFake`, etc) 🤔.

**Comment by syntactic-salt** [comment] 2022-05-03 17:37
It looks like this is actually an issue that's introduced by axe-core. axe-core uses setTimeout under the hood.

https://github.com/dequelabs/axe-core/issues/3055
